# Generated by Django 2.0.1 on 2018-01-18 18:07

from django.db import migrations


def create_subjects(apps, schema_editor):
    Subject = apps.get_model('planificacionVisitas', 'Subject')
    Subject.objects.create(name='Tutoria', color='#343a40')
    Subject.objects.create(name='Tecnico', color='#007bff')
    

class Migration(migrations.Migration):

    dependencies = [
        ('planificacionVisitas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_subjects),
    ]
