# Generated by Django 2.0.7 on 2018-08-18 17:45

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'Tutor'), (2, 'Técnico'), (3, 'Tutor Líder'), (4, 'Técnico Líder')], null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='DataApciAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_prof_capacitados', models.IntegerField()),
                ('minutos_uso', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
            ],
            options={
                'db_table': 'data_apci_academico',
            },
        ),
        migrations.CreateModel(
            name='NoAlumnosIngresados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_egb', models.CharField(max_length=30)),
                ('paralelo_a', models.FloatField()),
                ('paralelo_b', models.FloatField()),
                ('paralelo_c', models.FloatField()),
                ('total', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
                ('data_apci_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DataApciAcademico')),
            ],
            options={
                'db_table': 'no_alumnos_ingresados',
            },
        ),
        migrations.CreateModel(
            name='NoAlumnosTrabajando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_egb', models.CharField(max_length=30)),
                ('lenguaje', models.FloatField()),
                ('matematica', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
                ('data_apci_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DataApciAcademico')),
            ],
            options={
                'db_table': 'no_alumnos_trabajando',
            },
        ),
        migrations.CreateModel(
            name='NoLeccionesAprobadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_egb', models.CharField(max_length=30)),
                ('lenguaje', models.FloatField()),
                ('matematica', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
                ('data_apci_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DataApciAcademico')),
            ],
            options={
                'db_table': 'no_lecciones_aprobadas',
            },
        ),
        migrations.CreateModel(
            name='PedagogicalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.IntegerField()),
                ('extracurricular', models.TextField(null=True)),
                ('internet', models.PositiveSmallIntegerField(choices=[(1, 'No'), (2, 'Si')], null=True)),
                ('action_taken', models.TextField()),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'En progreso'), (2, 'Finalizado')], default=1, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
                ('data_apci_academico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DataApciAcademico')),
            ],
            options={
                'db_table': 'pedagogical_form',
            },
        ),
        migrations.CreateModel(
            name='PromedioAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_egb', models.CharField(max_length=30)),
                ('lenguaje', models.FloatField()),
                ('matematica', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
                ('data_apci_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DataApciAcademico')),
            ],
            options={
                'db_table': 'promedio_academico',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Periódica'), (2, 'Llamada'), (3, 'Incidencia')], null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Atendido'), (3, 'Rechazado')], default=1, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
            ],
            options={
                'db_table': 'requirement',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amie', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('address', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('workday', models.PositiveSmallIntegerField(choices=[(1, 'Matutina'), (2, 'Vespertina'), (3, 'Matutina/Vespertina')], null=True)),
                ('parish', models.CharField(max_length=100)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'No'), (2, 'Si')], null=True)),
                ('ambassador_in', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='TechnicalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(max_length=100)),
                ('observation', models.TextField(null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'En progreso'), (2, 'Finalizado')], default=1, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
                ('activity', models.ManyToManyField(to='accounts.Activity')),
            ],
            options={
                'db_table': 'technical_form',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planned', models.DateTimeField()),
                ('check_in', models.DateTimeField(null=True)),
                ('check_out', models.DateTimeField(null=True)),
                ('coordinates_lat_in', models.CharField(max_length=100, null=True)),
                ('coordinates_lon_in', models.CharField(max_length=100, null=True)),
                ('coordinates_lat_out', models.CharField(max_length=100, null=True)),
                ('coordinates_lon_out', models.CharField(max_length=100, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Pedagógica'), (2, 'Técnica'), (3, 'Ambas')], null=True)),
                ('observation', models.TextField(null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Realizada'), (3, 'No Realizada')], null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(null=True)),
                ('requirement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Requirement')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visit',
            },
        ),
        migrations.AddField(
            model_name='technicalform',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Visit'),
        ),
        migrations.AddField(
            model_name='school',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Sector'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.School'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedagogicalform',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Visit'),
        ),
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.ManyToManyField(to='accounts.Sector'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
