# Generated by Django 2.0.7 on 2018-08-07 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='coordinates_in',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='coordinates_out',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.School'),
        ),
    ]
