# Generated by Django 2.0.7 on 2018-09-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedagogicalform',
            name='visit_number',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Periódica'), (2, 'Llamada'), (3, 'Incidencia')], null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Realizada'), (3, 'No Realizada')], default=1, null=True),
        ),
    ]
