# Generated by Django 2.0.7 on 2018-08-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180806_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
