# Generated by Django 2.0.7 on 2018-10-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180914_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='parish',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ayacucho'), (2, 'Bolívar (Sagrario)'), (3, 'Carbo (Concepción)'), (4, 'Chongón'), (5, 'Febres Cordero'), (6, 'García Moreno'), (7, 'Letamendi'), (8, 'Nueve de Octubre'), (9, 'Olmedo (San Alejo)'), (10, 'Pascuales'), (11, 'Roca'), (12, 'Rocafuerte'), (13, 'Sucre'), (14, 'Tarqui'), (15, 'Urdaneta'), (16, 'Ximena'), (17, 'Juan Gómez Rendón (Progreso)'), (18, 'Puná'), (19, 'Tenguel'), (20, 'Posorja'), (21, 'El Morro')], null=True),
        ),
    ]
