# Generated by Django 2.0.7 on 2018-08-21 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180820_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 23, 47, 48, 30472)),
        ),
        migrations.AlterField(
            model_name='dataapciacademico',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 23, 47, 48, 31471)),
        ),
        migrations.AlterField(
            model_name='noalumnosingresados',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 23, 47, 48, 33470)),
        ),
        migrations.AlterField(
            model_name='noalumnostrabajando',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 23, 47, 48, 34469)),
        ),
        migrations.AlterField(
            model_name='noleccionesaprobadas',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 23, 47, 48, 32470)),
        ),
        migrations.AlterField(
            model_name='pedagogicalform',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 23, 47, 48, 35468)),
        ),
        migrations.AlterField(
            model_name='promedioacademico',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 23, 47, 48, 33470)),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 23, 47, 48, 28472)),
        ),
        migrations.AlterField(
            model_name='school',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 23, 47, 48, 27473)),
        ),
        migrations.AlterField(
            model_name='sector',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 23, 47, 48, 24474)),
        ),
        migrations.AlterField(
            model_name='technicalform',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 23, 47, 48, 30472)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 20, 23, 47, 48, 29472)),
        ),
    ]
