# Generated by Django 2.0.7 on 2018-08-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180820_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.CharField(default='Fernando Sánchez', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
