# Generated by Django 2.0.7 on 2018-08-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180821_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='description',
            field=models.TextField(default='Agrupar las escuelas por sectores', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
    ]
